title: Aditya Ramabadran
description: Machine learning research engineer with a background in mathematics and computer science.
url: "https://adityaramabadran.com"
baseurl: ""
repository: aditya-ramabadran/aditya-ramabadran.github.io

author:
  name: Aditya Ramabadran
  url: "https://adityaramabadran.com/"

github_username: aditya-ramabadran
twitter:
  username: a_ramabadran

markdown: kramdown
permalink: /writing/:year/:month/:day/:title/
timezone: America/Los_Angeles

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
